# Generated by Django 5.2 on 2025-04-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_category_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_normalized',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='article',
            name='title_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=250),
        ),
    ]
