# Generated by Django 5.2 on 2025-04-24 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_category_article_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Tolıq Atı (AÁÁ)')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Silteme (slug)')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='author_pics/', verbose_name='Profil Súwreti')),
                ('bio', models.TextField(blank=True, verbose_name='Biografiya/Haqqında')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Elektron Pochta')),
                ('website', models.URLField(blank=True, verbose_name='Web-sayt')),
            ],
            options={
                'verbose_name': 'Avtor',
                'verbose_name_plural': 'Avtorlar',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.author', verbose_name='Avtor'),
        ),
    ]
