# Generated by Django 5.2 on 2025-04-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_author_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Kóriwler Sanı'),
        ),
    ]
