# Generated by Django 5.2 on 2025-04-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='telegram_post_url',
            field=models.URLField(blank=True, help_text='Pikirlerdi jalǵaw ushın qollanılǵan Telegram postınıń tolıq siltemesi (https://...). Bos qaldırılsa, pikirler bólimi kórsetilmeydi.', max_length=500, null=True, verbose_name='Telegram Pikir URL'),
        ),
    ]
