# Generated by Django 5.2 on 2026-03-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_telegram_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='audio_summary',
            field=models.FileField(blank=True, null=True, upload_to='audio_summaries/', verbose_name='Audio Summary'),
        ),
    ]
